#!/usr/bin/env python3

from collections import namedtuple
import sys
import os
import json

sys.path.append(f'{os.path.dirname(os.path.realpath(__file__))}/../')
sys.path.append(f'{os.path.dirname(os.path.realpath(__file__))}/dependencies/wopwopd')
sys.path.append(f'{os.path.dirname(os.path.realpath(__file__))}/source')
#sys.path.append(f'{os.path.dirname(os.path.realpath(__file__))}/wopwop2aam')

from libopencopter import *
from libwopwopd import *
from source import compute_aero
from source import compute_acoustics
import numpy as np
import math
import argparse
from os import path, makedirs
from mpi4py import MPI

def calculate_sound_power_level(oaspl_db,area):

	spatial_avg_pressure = 0
	for i in range(23):
		for j in range(17):
			ms_pressure_temp = math.exp(oaspl_db[i][j]*0.1)
			spatial_avg_pressure = spatial_avg_pressure + ms_pressure_temp
			
	spatial_avg_pressure = spatial_avg_pressure/(np.size(oaspl_db))
	print("total number of grid points is", np.size(oaspl_db))

	sound_power_level = 10*np.log10(spatial_avg_pressure) + 10*np.log10(area)

	return sound_power_level

FlightCase = namedtuple("FlightCase", "aircraft condition wake_lengths total_wake computational_parameters results observer acoustics")

def build_flight_case(aircraft, flight_condition, computational_parameters, results, observer, acoustics):
	origins = [Vec3(aircraft['rotors'][r_idx]["origin"]) for r_idx in range(len(aircraft['rotors']))]
	radii = np.asarray([aircraft["rotors"][r_idx]["radius"] for r_idx in range(len(aircraft["rotors"]))])
	num_rotors = radii.size # aircraft["number_of_rotors"]
	V_inf = flight_condition["V_inf"]
	wake_dists = np.zeros(num_rotors)
	omegas =  np.asarray([flight_condition["omegas"][r_idx] for r_idx in range(num_rotors)])
	mus = V_inf/(np.abs(omegas)*radii)

	d_psi = computational_parameters["d_psi"]*math.pi/180.0

	wake_trail_distance = 3
	for o_idx, origin in enumerate(origins):
		for other_origin in origins:
			if mus[o_idx] == 0:
				delta_z = origin[2] - other_origin[2]

				# plus 1R to finish going past the other rotor, and then wake_trail_distance more radii after that
				wake_dists[o_idx] = max(wake_dists[o_idx], delta_z + 1 + wake_trail_distance)

			else:
				delta_x = origin[0] - other_origin[0]

				# plus 1R to finish going past the other rotor, and then wake_trail_distance more radii after that
				wake_dists[o_idx] = max(wake_dists[o_idx], delta_x + 1 + wake_trail_distance)

		if wake_dists[o_idx] <= 0:
			# if all others are upstream, just trail 6 radii behind
			wake_dists[o_idx] = wake_trail_distance

	wake_history_revs = np.zeros(wake_dists.size)

	for idx, mu in enumerate(mus):
		if mu != 0:
			wake_history_revs[idx] = round(wake_dists[idx]/(mu*2.0*math.pi)) # this is an array
		else:
			wake_history_revs[idx] = round(wake_dists[idx]/(0.1*2.0*math.pi)) # this is an array
	
	wake_history_length = np.round(2*math.pi/d_psi*wake_history_revs).astype(int)
	total_wake_history = wake_history_length.sum()
	
	return FlightCase(aircraft, flight_condition, wake_history_length.tolist(), total_wake_history, computational_parameters, results, observer, acoustics)

def main():
	# push check
	parser = argparse.ArgumentParser("computational_toolchain", description="computational pipeline")

	parser.add_argument(
		'-s',
		type=float,
		help="Non-dimensional longitudinal separation betwen rotors. A value of 0 has the edge the tip path planes touching. A positive value will move the rotor away from the from rotor",
		required=False
	)
	parser.add_argument(
		'-a',
		type=float,
		help="Shaft angle of attack of rotor system",
		required=False
	)
	parser.add_argument(
		'-d',
		type=float,
		help="Non-dimensional vertical separation between rotors. A value of 0 has the rotors in the same plane. A negative puts the rear rotor below the plane of the front rotor."
	)
	parser.add_argument(
		"-v",
		type=float,
		help="Advance ratio of the rotor system",
		required=False,
		default=None
	)
	parser.add_argument(
		"-c1",
		type=float,
		help="Collective pitch of the front rotor in degrees"
	)
	parser.add_argument(
		"-c2",
		type=float,
		help="Collective pitch of the rear rotor in degrees"
	)
	parser.add_argument(
		"-ct",
		type=float,
		help="Desired C_T for trim algo",
		default=0.008,
		required=False
	)
	parser.add_argument(
		"-r",
		type=int,
		help="Number of rotor revs to simulate",
		default=None, 
		required=False
	)
	parser.add_argument(
		"-w",
		type=int,
		help="Number of rotor revolutions to trail wake",
		default=4,
		required=False
	)
	parser.add_argument(
		"-ws",
		action='store_true',
		help="Save the last revolution of the wake to vtu files for visualization",
		default=False,
		required=False
	)
	parser.add_argument(
		"--aero",
		action='store_true',
		help="Compute aerodynamics",
		default=False,
		required=False
	)
	parser.add_argument(
		"--acoustics",
		action='store_true',
		help="Compute acoustics",
		default=False,
		required=False
	)
	parser.add_argument(
		"-fs",
		action='store_true',
		help="Full system acoustics only",
		default=False,
		required=False
	)
	parser.add_argument(
		"-ar",
		type=int,
		help="aoa restart index",
		default=0, 
		required=False
	)
	parser.add_argument(
		"-hr",
		type=int,
		help="h_sep restart index",
		default=0, 
		required=False
	)
	parser.add_argument(
		"-ci",
		type=int,
		help="Flight configuration index",
		default=None, 
		required=False
	)
	parser.add_argument(
		"--aam",
		action='store_true',
		help="Convert wopwop spheres to AAM spheres",
		default=False, 
		required=False
	)
	parser.add_argument(
		"--vtu_results",
		action='store_true',
		help="Save the out the slices defined by the results field",
		default=False, 
		required=False
	)
	parser.add_argument(
		"-input_geom",
		type= str,
		required=False
	)
	parser.add_argument(
		"-input_param",
		type= str,
		required=False
	)
	parser.add_argument(
		"-observer_param",
		type= str,
		required=False
	)
	parser.add_argument(
		"-acoustics_param",
		type= str, 
		required=False
	)

	parser.add_argument(
		"-case_file",
		type= str, 
		required=False
	)

	comm = MPI.COMM_WORLD
	rank = comm.Get_rank()

	args = parser.parse_args()

	cases = []

	if args.input_geom is None and args.case_file is None:
		print("-input_geom or -case_file must be specified on the command line")
		exit(-1)

	geom = []
	if args.input_geom is not None:
		geom_directory = path.dirname(path.realpath(args.input_geom))

		with open(args.input_geom) as geom_file:
			geom = json.load(geom_file)
	elif args.case_file is not None:
		
		with open(args.case_file) as case_file:
			ac_list = json.load(case_file)

		for ac in ac_list:
			geom_directory = path.dirname(path.realpath(args.case_file))

			with open(ac) as geom_file:
				geom = geom + json.load(geom_file)

	param = None
	if args.input_param is not None:
		with open(args.input_param) as param_file:
			param = json.load(param_file)

	input_observer = None
	input_acoustics = None
	input_flight_conditions = None
	input_computational_parameters = None
	input_results = None

	if args.observer_param is not None:
		with open(args.observer_param) as param_file:
			obs_param = json.load(param_file)
			input_observer = obs_param["observer"]

	if args.acoustics_param is not None:
		with open(args.acoustics_param) as param_file:
			acoustic_param = json.load(param_file)
			input_acoustics = acoustic_param["acoustic_config"]

	if param is not None:
		input_flight_conditions = param["flight_conditions"]
		input_computational_parameters = param["computational_parameters"]
		input_results = param["results"] if "results" in param else None
	
	flat_cases = []
	for aircraft in geom:
		if 'parameter_file' in aircraft:
			ac_param = None
			with open(aircraft['parameter_file']) as param_file:
				ac_param = json.load(param_file)

		if input_flight_conditions is not None:
			flight_conditions = input_flight_conditions
		elif ac_param is not None:
			flight_conditions = ac_param['flight_conditions']
		else:
			print("No flight_conditions specified on command line or aircraft file")
			exit(-1)

		if input_computational_parameters is not None:
			computational_parameters = input_computational_parameters
		elif ac_param is not None:
			computational_parameters = ac_param['computational_parameters']
		else:
			print("No computational_parameters specified on command line or aircraft file")
			exit(-1)

		results = None
		if input_results is not None:
			results = input_results
		elif ac_param is not None:
			if 'results' in ac_param:
				results = ac_param['results']

		if args.ci is None:
			for flight_condition in flight_conditions:
				if input_observer is not None:
					observer = input_observer
				elif 'observer_file' in flight_condition:
					ac_observers = None
					with open(flight_condition['observer_file']) as param_file:
						ac_observers = json.load(param_file)
						observer = ac_observers["observer"]

				if input_acoustics is not None:
					acoustics = input_acoustics
				elif 'acoustics_file' in flight_condition:
					ac_acoustics = None
					with open(flight_condition['acoustics_file']) as param_file:
						ac_acoustics = json.load(param_file)
						acoustics = ac_acoustics["acoustic_config"]

				flat_cases.append(build_flight_case(aircraft, flight_condition, computational_parameters, results, observer, acoustics))
		else:
			flight_condition = flight_conditions[args.ci]
			if input_observer is not None:
				observer = input_observer
			elif 'observer_file' in flight_condition:
				ac_observers = None
				with open(flight_condition['observer_file']) as param_file:
					ac_observers = json.load(param_file)
					observer = ac_observers["observer"]

			if input_acoustics is not None:
				acoustics = input_acoustics
			elif 'acoustics_file' in flight_condition:
				ac_acoustics = None
				with open(flight_condition['acoustics_file']) as param_file:
					ac_acoustics = json.load(param_file)
					acoustics = ac_acoustics["acoustic_config"]

			flat_cases.append(build_flight_case(aircraft, flight_condition, computational_parameters, results, observer, acoustics))

	# sort cases by total number of wake points. This will helps with load balancing
	# across many cores
	flat_cases = sorted(flat_cases, key=lambda tup: tup[3])
	
	total_procs = comm.Get_size()

	cases_per_core = int(len(flat_cases)/total_procs)
	left_over_cases = len(flat_cases)%total_procs

	lock_file_name = f'./iris.lock'

	lock_exists = os.path.exists(lock_file_name)

	comm.barrier()

	if rank == 0:
		if not lock_exists:
			lock_file = open(lock_file_name, 'w')
	
	comm.barrier()

	case_slice = []
	for case_idx in range(len(flat_cases)):
		if case_idx*total_procs + rank < len(flat_cases):
			case_slice.append(flat_cases[case_idx*total_procs + rank])
	
	print(f'Rank {rank}: len(case_slice): {len(case_slice)}')

	prog_file_name = f"rank_{rank}.prog"
	start_idx = 0
	acoustic_start_idx = 0

	prog_file_exists = os.path.exists(prog_file_name)

	do_compute_aero = args.aero

	print(f'Prog file: {prog_file_name}')
	if prog_file_exists:
		with open(prog_file_name, "r") as prog_file:
			prog_lines = prog_file.readlines()
			num_lines = len(prog_lines)

			print(f"{rank}: number of lines in prog file: {num_lines}")
			if num_lines > 0:
				restart_type = prog_lines[0].split(" ")[0]
				if restart_type == "acoustics":
					acoustic_start_idx = int(prog_lines[0].split(" ")[1]) + 1
					do_compute_aero = False
				else:
					start_idx = int(prog_lines[0].split(" ")[1]) + 1

	if (prog_file_exists and lock_exists) or (not prog_file_exists and not lock_exists):
		with open(prog_file_name, "w+") as prog_file:
			for idx, case in enumerate(case_slice[start_idx:]):
				flight_condition = case.condition
				computational_parameters = case.computational_parameters
				results = case.results
				observer = case.observer
				acoustics = case.acoustics

				aircraft = case.aircraft
				V_inf = float(case.condition["V_inf"])
				aoa = float(case.condition["aoa"])
				aoa_dir = f'aoa_{aoa:.3}'
				V_inf_dir = f'V_inf_{V_inf:.3}'

				state_dir = ''
				if "c_t" in flight_condition:
					state_dir = f'ct{"_".join([f"{c_t:.6f}" for c_t in flight_condition["c_t"]])}'
				elif "T" in flight_condition:
					state_dir = f'T{"_".join([f"{T:.4f}" for T in flight_condition["T"]])}'
				else:
					state_dir = f'theta{"_".join([f"{theta:.2f}" for theta in flight_condition["collective"]])}'

				if "name" in flight_condition:
					root_path = f'./{case.aircraft["name"]}/{flight_condition["name"]}'
				else:
					root_path = f'./{case.aircraft["name"]}/{aoa_dir}/{V_inf_dir}/{state_dir}'

				if not path.isdir(root_path):
					makedirs(root_path, exist_ok=True)

				log_file_name = f"{root_path}/run_{rank}.log"
				with open(log_file_name, "w+") as log_file:

					log_file.write('\n')
					log_file.write(f'Running sim with aoa: {aoa}\n')
					log_file.write( '----------------------------------------------\n')

					flight_condition["V_inf"] = V_inf if args.v is None else args.v

					if args.r is not None:
						log_file.write(f"Setting post_conv_revolutions to {args.r} due to command line override\n")
						computational_parameters['post_conv_revolutions'] = args.r

					log_file.write("simulating aero\n")
					wopwop_cases = compute_aero.compute_aero(log_file, args, f'{root_path}/', do_compute_aero, aircraft, flight_condition, computational_parameters, results, geom_directory, observer, acoustics, case.wake_lengths)
					cases = cases + wopwop_cases

					for case in wopwop_cases:
						write_namelist(case.namelist, f'{case.globalFolderName}/{case.caseNameFile}')

					prog_file.seek(0)
					prog_file.write(f'aero {idx + start_idx}')
					prog_file.flush()

			if args.acoustics:
				print("writing acoutics to prog file")
				prog_file.seek(0)
				prog_file.write(f'acoustics -1')
				prog_file.flush()

		if not args.acoustics:
			os.remove(prog_file_name)

	else:
		print(f"{rank}: Waiting on other procs to finish")

	wopwop_results = []
	if args.acoustics:
		open_mode = "r+" if prog_file_exists else "w+"
		with open(prog_file_name, open_mode) as prog_file:
			for case_idx, case in enumerate(cases[acoustic_start_idx:]):
				print("calculating acoustics")
				case_list = CaseList()
				case_list.cases = [case]

				compute_acoustics.compute_acoustics(case_list, rank)

				prog_file.seek(0, 0)
				prog_file.write(f'acoustics {case_idx + acoustic_start_idx}')
				prog_file.flush()

		os.remove(prog_file_name)
	elif (acoustics is not None) and (observer is not None):
		case_list = CaseList()
		case_list.cases = cases

		#void write_caselist_custom_name(ref CaseList case_list, string directory, string caselist_filename) {
		write_caselist_custom_name(case_list, "./", f'cases_{rank}.nam')

		
	# wait for all other procs to finish.
	comm.barrier()

	if rank == 0:
		os.remove(lock_file_name)

	print("done")


if __name__ == "__main__":
	main()
	print("exiting main.py")
